name: tobler
channels:
  - conda-forge
  - defaults
dependencies:
  - jupyterlab
  - numpy
  - geopandas >=0.7
  - pandas
  - numpy
  - rasterio
  - rasterstats
  - statsmodels
  - scikit-learn
  - scipy
  - libpysal
  - tqdm
  - pip
